/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponseDto
 */
export interface AuthResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AuthResponseDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    refreshToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthResponseDto
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the AuthResponseDto interface.
 */
export function instanceOfAuthResponseDto(value: object): value is AuthResponseDto {
    return true;
}

export function AuthResponseDtoFromJSON(json: any): AuthResponseDto {
    return AuthResponseDtoFromJSONTyped(json, false);
}

export function AuthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'token': json['token'] == null ? undefined : json['token'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function AuthResponseDtoToJSON(json: any): AuthResponseDto {
    return AuthResponseDtoToJSONTyped(json, false);
}

export function AuthResponseDtoToJSONTyped(value?: AuthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'email': value['email'],
        'avatar': value['avatar'],
        'token': value['token'],
        'refreshToken': value['refreshToken'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

