/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    confirmNewPassword: string;
}

/**
 * Check if a given object implements the ChangePasswordDto interface.
 */
export function instanceOfChangePasswordDto(value: object): value is ChangePasswordDto {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('confirmNewPassword' in value) || value['confirmNewPassword'] === undefined) return false;
    return true;
}

export function ChangePasswordDtoFromJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoFromJSONTyped(json, false);
}

export function ChangePasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
        'confirmNewPassword': json['confirmNewPassword'],
    };
}

export function ChangePasswordDtoToJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoToJSONTyped(json, false);
}

export function ChangePasswordDtoToJSONTyped(value?: ChangePasswordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
        'confirmNewPassword': value['confirmNewPassword'],
    };
}

