/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyBalanceDto
 */
export interface CurrencyBalanceDto {
    /**
     * 
     * @type {string}
     * @memberof CurrencyBalanceDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrencyBalanceDto
     */
    currencySymbol?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CurrencyBalanceDto
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyBalanceDto
     */
    totalSpent?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyBalanceDto
     */
    totalOwed?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyBalanceDto
     */
    tripCount?: number;
}

/**
 * Check if a given object implements the CurrencyBalanceDto interface.
 */
export function instanceOfCurrencyBalanceDto(value: object): value is CurrencyBalanceDto {
    return true;
}

export function CurrencyBalanceDtoFromJSON(json: any): CurrencyBalanceDto {
    return CurrencyBalanceDtoFromJSONTyped(json, false);
}

export function CurrencyBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'currencySymbol': json['currencySymbol'] == null ? undefined : json['currencySymbol'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'totalSpent': json['totalSpent'] == null ? undefined : json['totalSpent'],
        'totalOwed': json['totalOwed'] == null ? undefined : json['totalOwed'],
        'tripCount': json['tripCount'] == null ? undefined : json['tripCount'],
    };
}

export function CurrencyBalanceDtoToJSON(json: any): CurrencyBalanceDto {
    return CurrencyBalanceDtoToJSONTyped(json, false);
}

export function CurrencyBalanceDtoToJSONTyped(value?: CurrencyBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'currencySymbol': value['currencySymbol'],
        'balance': value['balance'],
        'totalSpent': value['totalSpent'],
        'totalOwed': value['totalOwed'],
        'tripCount': value['tripCount'],
    };
}

