/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseSplitDto
 */
export interface ExpenseSplitDto {
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseSplitDto
     */
    userName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitDto
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitDto
     */
    percentage?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ExpenseSplitDto
     */
    isPaid?: boolean;
}

/**
 * Check if a given object implements the ExpenseSplitDto interface.
 */
export function instanceOfExpenseSplitDto(value: object): value is ExpenseSplitDto {
    return true;
}

export function ExpenseSplitDtoFromJSON(json: any): ExpenseSplitDto {
    return ExpenseSplitDtoFromJSONTyped(json, false);
}

export function ExpenseSplitDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseSplitDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'isPaid': json['isPaid'] == null ? undefined : json['isPaid'],
    };
}

export function ExpenseSplitDtoToJSON(json: any): ExpenseSplitDto {
    return ExpenseSplitDtoToJSONTyped(json, false);
}

export function ExpenseSplitDtoToJSONTyped(value?: ExpenseSplitDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'userName': value['userName'],
        'amount': value['amount'],
        'percentage': value['percentage'],
        'isPaid': value['isPaid'],
    };
}

