/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseSplitCreateDto
 */
export interface ExpenseSplitCreateDto {
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitCreateDto
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitCreateDto
     */
    amount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSplitCreateDto
     */
    percentage?: number | null;
}

/**
 * Check if a given object implements the ExpenseSplitCreateDto interface.
 */
export function instanceOfExpenseSplitCreateDto(value: object): value is ExpenseSplitCreateDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ExpenseSplitCreateDtoFromJSON(json: any): ExpenseSplitCreateDto {
    return ExpenseSplitCreateDtoFromJSONTyped(json, false);
}

export function ExpenseSplitCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseSplitCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function ExpenseSplitCreateDtoToJSON(json: any): ExpenseSplitCreateDto {
    return ExpenseSplitCreateDtoToJSONTyped(json, false);
}

export function ExpenseSplitCreateDtoToJSONTyped(value?: ExpenseSplitCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

