/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpenseSplitCreateDto } from './ExpenseSplitCreateDto';
import {
    ExpenseSplitCreateDtoFromJSON,
    ExpenseSplitCreateDtoFromJSONTyped,
    ExpenseSplitCreateDtoToJSON,
    ExpenseSplitCreateDtoToJSONTyped,
} from './ExpenseSplitCreateDto';

/**
 * 
 * @export
 * @interface ExpenseCreateDto
 */
export interface ExpenseCreateDto {
    /**
     * 
     * @type {number}
     * @memberof ExpenseCreateDto
     */
    tripId: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCreateDto
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseCreateDto
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseCreateDto
     */
    paidByUserId: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCreateDto
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCreateDto
     */
    splitType: string;
    /**
     * 
     * @type {Array<ExpenseSplitCreateDto>}
     * @memberof ExpenseCreateDto
     */
    splits?: Array<ExpenseSplitCreateDto> | null;
}

/**
 * Check if a given object implements the ExpenseCreateDto interface.
 */
export function instanceOfExpenseCreateDto(value: object): value is ExpenseCreateDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('paidByUserId' in value) || value['paidByUserId'] === undefined) return false;
    if (!('splitType' in value) || value['splitType'] === undefined) return false;
    return true;
}

export function ExpenseCreateDtoFromJSON(json: any): ExpenseCreateDto {
    return ExpenseCreateDtoFromJSONTyped(json, false);
}

export function ExpenseCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'description': json['description'],
        'amount': json['amount'],
        'paidByUserId': json['paidByUserId'],
        'category': json['category'] == null ? undefined : json['category'],
        'splitType': json['splitType'],
        'splits': json['splits'] == null ? undefined : ((json['splits'] as Array<any>).map(ExpenseSplitCreateDtoFromJSON)),
    };
}

export function ExpenseCreateDtoToJSON(json: any): ExpenseCreateDto {
    return ExpenseCreateDtoToJSONTyped(json, false);
}

export function ExpenseCreateDtoToJSONTyped(value?: ExpenseCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'description': value['description'],
        'amount': value['amount'],
        'paidByUserId': value['paidByUserId'],
        'category': value['category'],
        'splitType': value['splitType'],
        'splits': value['splits'] == null ? undefined : ((value['splits'] as Array<any>).map(ExpenseSplitCreateDtoToJSON)),
    };
}

