/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpenseSplitDto } from './ExpenseSplitDto';
import {
    ExpenseSplitDtoFromJSON,
    ExpenseSplitDtoFromJSONTyped,
    ExpenseSplitDtoToJSON,
    ExpenseSplitDtoToJSONTyped,
} from './ExpenseSplitDto';

/**
 * 
 * @export
 * @interface ExpenseDto
 */
export interface ExpenseDto {
    /**
     * 
     * @type {number}
     * @memberof ExpenseDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseDto
     */
    tripId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseDto
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseDto
     */
    paidByUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDto
     */
    paidByName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ExpenseDto
     */
    expenseDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDto
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDto
     */
    splitType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseDto
     */
    splitCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof ExpenseDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<ExpenseSplitDto>}
     * @memberof ExpenseDto
     */
    splits?: Array<ExpenseSplitDto> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ExpenseDto
     */
    hasSettlements?: boolean;
}

/**
 * Check if a given object implements the ExpenseDto interface.
 */
export function instanceOfExpenseDto(value: object): value is ExpenseDto {
    return true;
}

export function ExpenseDtoFromJSON(json: any): ExpenseDto {
    return ExpenseDtoFromJSONTyped(json, false);
}

export function ExpenseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'paidByUserId': json['paidByUserId'] == null ? undefined : json['paidByUserId'],
        'paidByName': json['paidByName'] == null ? undefined : json['paidByName'],
        'expenseDate': json['expenseDate'] == null ? undefined : (new Date(json['expenseDate'])),
        'category': json['category'] == null ? undefined : json['category'],
        'splitType': json['splitType'] == null ? undefined : json['splitType'],
        'splitCount': json['splitCount'] == null ? undefined : json['splitCount'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'splits': json['splits'] == null ? undefined : ((json['splits'] as Array<any>).map(ExpenseSplitDtoFromJSON)),
        'hasSettlements': json['hasSettlements'] == null ? undefined : json['hasSettlements'],
    };
}

export function ExpenseDtoToJSON(json: any): ExpenseDto {
    return ExpenseDtoToJSONTyped(json, false);
}

export function ExpenseDtoToJSONTyped(value?: ExpenseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tripId': value['tripId'],
        'currency': value['currency'],
        'description': value['description'],
        'amount': value['amount'],
        'paidByUserId': value['paidByUserId'],
        'paidByName': value['paidByName'],
        'expenseDate': value['expenseDate'] == null ? value['expenseDate'] : value['expenseDate'].toISOString(),
        'category': value['category'],
        'splitType': value['splitType'],
        'splitCount': value['splitCount'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'splits': value['splits'] == null ? undefined : ((value['splits'] as Array<any>).map(ExpenseSplitDtoToJSON)),
        'hasSettlements': value['hasSettlements'],
    };
}

