/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinTripDto
 */
export interface JoinTripDto {
    /**
     * 
     * @type {string}
     * @memberof JoinTripDto
     */
    inviteToken: string;
}

/**
 * Check if a given object implements the JoinTripDto interface.
 */
export function instanceOfJoinTripDto(value: object): value is JoinTripDto {
    if (!('inviteToken' in value) || value['inviteToken'] === undefined) return false;
    return true;
}

export function JoinTripDtoFromJSON(json: any): JoinTripDto {
    return JoinTripDtoFromJSONTyped(json, false);
}

export function JoinTripDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinTripDto {
    if (json == null) {
        return json;
    }
    return {
        
        'inviteToken': json['inviteToken'],
    };
}

export function JoinTripDtoToJSON(json: any): JoinTripDto {
    return JoinTripDtoToJSONTyped(json, false);
}

export function JoinTripDtoToJSONTyped(value?: JoinTripDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inviteToken': value['inviteToken'],
    };
}

