/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinTripResponse
 */
export interface JoinTripResponse {
    /**
     * 
     * @type {string}
     * @memberof JoinTripResponse
     */
    message?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoinTripResponse
     */
    tripId?: number;
}

/**
 * Check if a given object implements the JoinTripResponse interface.
 */
export function instanceOfJoinTripResponse(value: object): value is JoinTripResponse {
    return true;
}

export function JoinTripResponseFromJSON(json: any): JoinTripResponse {
    return JoinTripResponseFromJSONTyped(json, false);
}

export function JoinTripResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinTripResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
    };
}

export function JoinTripResponseToJSON(json: any): JoinTripResponse {
    return JoinTripResponseToJSONTyped(json, false);
}

export function JoinTripResponseToJSONTyped(value?: JoinTripResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'tripId': value['tripId'],
    };
}

