/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunningTransactionItemDto } from './RunningTransactionItemDto';
import {
    RunningTransactionItemDtoFromJSON,
    RunningTransactionItemDtoFromJSONTyped,
    RunningTransactionItemDtoToJSON,
    RunningTransactionItemDtoToJSONTyped,
} from './RunningTransactionItemDto';

/**
 * 
 * @export
 * @interface MemberExpenseBreakdownDto
 */
export interface MemberExpenseBreakdownDto {
    /**
     * 
     * @type {number}
     * @memberof MemberExpenseBreakdownDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof MemberExpenseBreakdownDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemberExpenseBreakdownDto
     */
    userAvatar?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MemberExpenseBreakdownDto
     */
    isArchived?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MemberExpenseBreakdownDto
     */
    tripId?: number;
    /**
     * 
     * @type {string}
     * @memberof MemberExpenseBreakdownDto
     */
    tripName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemberExpenseBreakdownDto
     */
    currency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MemberExpenseBreakdownDto
     */
    netBalance?: number;
    /**
     * 
     * @type {Array<RunningTransactionItemDto>}
     * @memberof MemberExpenseBreakdownDto
     */
    transactions?: Array<RunningTransactionItemDto> | null;
}

/**
 * Check if a given object implements the MemberExpenseBreakdownDto interface.
 */
export function instanceOfMemberExpenseBreakdownDto(value: object): value is MemberExpenseBreakdownDto {
    return true;
}

export function MemberExpenseBreakdownDtoFromJSON(json: any): MemberExpenseBreakdownDto {
    return MemberExpenseBreakdownDtoFromJSONTyped(json, false);
}

export function MemberExpenseBreakdownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberExpenseBreakdownDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'userAvatar': json['userAvatar'] == null ? undefined : json['userAvatar'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'tripName': json['tripName'] == null ? undefined : json['tripName'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'netBalance': json['netBalance'] == null ? undefined : json['netBalance'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(RunningTransactionItemDtoFromJSON)),
    };
}

export function MemberExpenseBreakdownDtoToJSON(json: any): MemberExpenseBreakdownDto {
    return MemberExpenseBreakdownDtoToJSONTyped(json, false);
}

export function MemberExpenseBreakdownDtoToJSONTyped(value?: MemberExpenseBreakdownDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'userName': value['userName'],
        'userAvatar': value['userAvatar'],
        'isArchived': value['isArchived'],
        'tripId': value['tripId'],
        'tripName': value['tripName'],
        'currency': value['currency'],
        'netBalance': value['netBalance'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(RunningTransactionItemDtoToJSON)),
    };
}

