/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunningTransactionItemDto
 */
export interface RunningTransactionItemDto {
    /**
     * 
     * @type {Date}
     * @memberof RunningTransactionItemDto
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof RunningTransactionItemDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RunningTransactionItemDto
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RunningTransactionItemDto
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof RunningTransactionItemDto
     */
    runningBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof RunningTransactionItemDto
     */
    transactionId?: number;
    /**
     * 
     * @type {number}
     * @memberof RunningTransactionItemDto
     */
    expenseId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RunningTransactionItemDto
     */
    paidByName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RunningTransactionItemDto
     */
    totalExpenseAmount?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof RunningTransactionItemDto
     */
    isUserPayer?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RunningTransactionItemDto
     */
    settlementId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RunningTransactionItemDto
     */
    fromUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RunningTransactionItemDto
     */
    toUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RunningTransactionItemDto
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the RunningTransactionItemDto interface.
 */
export function instanceOfRunningTransactionItemDto(value: object): value is RunningTransactionItemDto {
    return true;
}

export function RunningTransactionItemDtoFromJSON(json: any): RunningTransactionItemDto {
    return RunningTransactionItemDtoFromJSONTyped(json, false);
}

export function RunningTransactionItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunningTransactionItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'runningBalance': json['runningBalance'] == null ? undefined : json['runningBalance'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'expenseId': json['expenseId'] == null ? undefined : json['expenseId'],
        'paidByName': json['paidByName'] == null ? undefined : json['paidByName'],
        'totalExpenseAmount': json['totalExpenseAmount'] == null ? undefined : json['totalExpenseAmount'],
        'isUserPayer': json['isUserPayer'] == null ? undefined : json['isUserPayer'],
        'settlementId': json['settlementId'] == null ? undefined : json['settlementId'],
        'fromUserName': json['fromUserName'] == null ? undefined : json['fromUserName'],
        'toUserName': json['toUserName'] == null ? undefined : json['toUserName'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function RunningTransactionItemDtoToJSON(json: any): RunningTransactionItemDto {
    return RunningTransactionItemDtoToJSONTyped(json, false);
}

export function RunningTransactionItemDtoToJSONTyped(value?: RunningTransactionItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'description': value['description'],
        'type': value['type'],
        'amount': value['amount'],
        'runningBalance': value['runningBalance'],
        'transactionId': value['transactionId'],
        'expenseId': value['expenseId'],
        'paidByName': value['paidByName'],
        'totalExpenseAmount': value['totalExpenseAmount'],
        'isUserPayer': value['isUserPayer'],
        'settlementId': value['settlementId'],
        'fromUserName': value['fromUserName'],
        'toUserName': value['toUserName'],
        'notes': value['notes'],
    };
}

