/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettlementSuggestionDto
 */
export interface SettlementSuggestionDto {
    /**
     * 
     * @type {number}
     * @memberof SettlementSuggestionDto
     */
    fromUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof SettlementSuggestionDto
     */
    fromUserName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SettlementSuggestionDto
     */
    toUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof SettlementSuggestionDto
     */
    toUserName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SettlementSuggestionDto
     */
    amount?: number;
}

/**
 * Check if a given object implements the SettlementSuggestionDto interface.
 */
export function instanceOfSettlementSuggestionDto(value: object): value is SettlementSuggestionDto {
    return true;
}

export function SettlementSuggestionDtoFromJSON(json: any): SettlementSuggestionDto {
    return SettlementSuggestionDtoFromJSONTyped(json, false);
}

export function SettlementSuggestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettlementSuggestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fromUserId': json['fromUserId'] == null ? undefined : json['fromUserId'],
        'fromUserName': json['fromUserName'] == null ? undefined : json['fromUserName'],
        'toUserId': json['toUserId'] == null ? undefined : json['toUserId'],
        'toUserName': json['toUserName'] == null ? undefined : json['toUserName'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function SettlementSuggestionDtoToJSON(json: any): SettlementSuggestionDto {
    return SettlementSuggestionDtoToJSONTyped(json, false);
}

export function SettlementSuggestionDtoToJSONTyped(value?: SettlementSuggestionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromUserId': value['fromUserId'],
        'fromUserName': value['fromUserName'],
        'toUserId': value['toUserId'],
        'toUserName': value['toUserName'],
        'amount': value['amount'],
    };
}

