/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettlementDto
 */
export interface SettlementDto {
    /**
     * 
     * @type {number}
     * @memberof SettlementDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof SettlementDto
     */
    tripId?: number;
    /**
     * 
     * @type {string}
     * @memberof SettlementDto
     */
    currency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SettlementDto
     */
    fromUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof SettlementDto
     */
    fromUserName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SettlementDto
     */
    toUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof SettlementDto
     */
    toUserName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SettlementDto
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof SettlementDto
     */
    settlementDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof SettlementDto
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the SettlementDto interface.
 */
export function instanceOfSettlementDto(value: object): value is SettlementDto {
    return true;
}

export function SettlementDtoFromJSON(json: any): SettlementDto {
    return SettlementDtoFromJSONTyped(json, false);
}

export function SettlementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettlementDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'fromUserId': json['fromUserId'] == null ? undefined : json['fromUserId'],
        'fromUserName': json['fromUserName'] == null ? undefined : json['fromUserName'],
        'toUserId': json['toUserId'] == null ? undefined : json['toUserId'],
        'toUserName': json['toUserName'] == null ? undefined : json['toUserName'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'settlementDate': json['settlementDate'] == null ? undefined : (new Date(json['settlementDate'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function SettlementDtoToJSON(json: any): SettlementDto {
    return SettlementDtoToJSONTyped(json, false);
}

export function SettlementDtoToJSONTyped(value?: SettlementDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tripId': value['tripId'],
        'currency': value['currency'],
        'fromUserId': value['fromUserId'],
        'fromUserName': value['fromUserName'],
        'toUserId': value['toUserId'],
        'toUserName': value['toUserName'],
        'amount': value['amount'],
        'settlementDate': value['settlementDate'] == null ? value['settlementDate'] : value['settlementDate'].toISOString(),
        'notes': value['notes'],
    };
}

