/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettlementCreateDto
 */
export interface SettlementCreateDto {
    /**
     * 
     * @type {number}
     * @memberof SettlementCreateDto
     */
    tripId: number;
    /**
     * 
     * @type {number}
     * @memberof SettlementCreateDto
     */
    fromUserId: number;
    /**
     * 
     * @type {number}
     * @memberof SettlementCreateDto
     */
    toUserId: number;
    /**
     * 
     * @type {number}
     * @memberof SettlementCreateDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof SettlementCreateDto
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the SettlementCreateDto interface.
 */
export function instanceOfSettlementCreateDto(value: object): value is SettlementCreateDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('fromUserId' in value) || value['fromUserId'] === undefined) return false;
    if (!('toUserId' in value) || value['toUserId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function SettlementCreateDtoFromJSON(json: any): SettlementCreateDto {
    return SettlementCreateDtoFromJSONTyped(json, false);
}

export function SettlementCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettlementCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'fromUserId': json['fromUserId'],
        'toUserId': json['toUserId'],
        'amount': json['amount'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function SettlementCreateDtoToJSON(json: any): SettlementCreateDto {
    return SettlementCreateDtoToJSONTyped(json, false);
}

export function SettlementCreateDtoToJSONTyped(value?: SettlementCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'fromUserId': value['fromUserId'],
        'toUserId': value['toUserId'],
        'amount': value['amount'],
        'notes': value['notes'],
    };
}

