/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripMemberDto } from './TripMemberDto';
import {
    TripMemberDtoFromJSON,
    TripMemberDtoFromJSONTyped,
    TripMemberDtoToJSON,
    TripMemberDtoToJSONTyped,
} from './TripMemberDto';

/**
 * 
 * @export
 * @interface TripDto
 */
export interface TripDto {
    /**
     * 
     * @type {number}
     * @memberof TripDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TripDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripDto
     */
    currency?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TripDto
     */
    isArchived?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TripDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TripDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TripDto
     */
    memberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TripDto
     */
    totalExpenses?: number;
    /**
     * 
     * @type {Date}
     * @memberof TripDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<TripMemberDto>}
     * @memberof TripDto
     */
    members?: Array<TripMemberDto> | null;
}

/**
 * Check if a given object implements the TripDto interface.
 */
export function instanceOfTripDto(value: object): value is TripDto {
    return true;
}

export function TripDtoFromJSON(json: any): TripDto {
    return TripDtoFromJSONTyped(json, false);
}

export function TripDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'totalExpenses': json['totalExpenses'] == null ? undefined : json['totalExpenses'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(TripMemberDtoFromJSON)),
    };
}

export function TripDtoToJSON(json: any): TripDto {
    return TripDtoToJSONTyped(json, false);
}

export function TripDtoToJSONTyped(value?: TripDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'currency': value['currency'],
        'isArchived': value['isArchived'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'memberCount': value['memberCount'],
        'totalExpenses': value['totalExpenses'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(TripMemberDtoToJSON)),
    };
}

