/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripMemberDto
 */
export interface TripMemberDto {
    /**
     * 
     * @type {number}
     * @memberof TripMemberDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TripMemberDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof TripMemberDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripMemberDto
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripMemberDto
     */
    role?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripMemberDto
     */
    joinedAt?: Date;
}

/**
 * Check if a given object implements the TripMemberDto interface.
 */
export function instanceOfTripMemberDto(value: object): value is TripMemberDto {
    return true;
}

export function TripMemberDtoFromJSON(json: any): TripMemberDto {
    return TripMemberDtoFromJSONTyped(json, false);
}

export function TripMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripMemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'role': json['role'] == null ? undefined : json['role'],
        'joinedAt': json['joinedAt'] == null ? undefined : (new Date(json['joinedAt'])),
    };
}

export function TripMemberDtoToJSON(json: any): TripMemberDto {
    return TripMemberDtoToJSONTyped(json, false);
}

export function TripMemberDtoToJSONTyped(value?: TripMemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'name': value['name'],
        'avatar': value['avatar'],
        'role': value['role'],
        'joinedAt': value['joinedAt'] == null ? value['joinedAt'] : value['joinedAt'].toISOString(),
    };
}

