/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripCreateDto
 */
export interface TripCreateDto {
    /**
     * 
     * @type {string}
     * @memberof TripCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TripCreateDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripCreateDto
     */
    currency?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripCreateDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TripCreateDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof TripCreateDto
     */
    memberIds?: Array<number> | null;
}

/**
 * Check if a given object implements the TripCreateDto interface.
 */
export function instanceOfTripCreateDto(value: object): value is TripCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TripCreateDtoFromJSON(json: any): TripCreateDto {
    return TripCreateDtoFromJSONTyped(json, false);
}

export function TripCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'memberIds': json['memberIds'] == null ? undefined : json['memberIds'],
    };
}

export function TripCreateDtoToJSON(json: any): TripCreateDto {
    return TripCreateDtoToJSONTyped(json, false);
}

export function TripCreateDtoToJSONTyped(value?: TripCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'currency': value['currency'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'memberIds': value['memberIds'],
    };
}

