/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripSummaryDto
 */
export interface TripSummaryDto {
    /**
     * 
     * @type {number}
     * @memberof TripSummaryDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TripSummaryDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripSummaryDto
     */
    currency?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripSummaryDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TripSummaryDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TripSummaryDto
     */
    memberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TripSummaryDto
     */
    totalExpenses?: number;
}

/**
 * Check if a given object implements the TripSummaryDto interface.
 */
export function instanceOfTripSummaryDto(value: object): value is TripSummaryDto {
    return true;
}

export function TripSummaryDtoFromJSON(json: any): TripSummaryDto {
    return TripSummaryDtoFromJSONTyped(json, false);
}

export function TripSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'totalExpenses': json['totalExpenses'] == null ? undefined : json['totalExpenses'],
    };
}

export function TripSummaryDtoToJSON(json: any): TripSummaryDto {
    return TripSummaryDtoToJSONTyped(json, false);
}

export function TripSummaryDtoToJSONTyped(value?: TripSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'currency': value['currency'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'memberCount': value['memberCount'],
        'totalExpenses': value['totalExpenses'],
    };
}

