/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripInviteDto
 */
export interface TripInviteDto {
    /**
     * 
     * @type {number}
     * @memberof TripInviteDto
     */
    tripId?: number;
    /**
     * 
     * @type {string}
     * @memberof TripInviteDto
     */
    tripName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripInviteDto
     */
    inviteLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripInviteDto
     */
    inviteToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripInviteDto
     */
    expiryDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof TripInviteDto
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the TripInviteDto interface.
 */
export function instanceOfTripInviteDto(value: object): value is TripInviteDto {
    return true;
}

export function TripInviteDtoFromJSON(json: any): TripInviteDto {
    return TripInviteDtoFromJSONTyped(json, false);
}

export function TripInviteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripInviteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'tripName': json['tripName'] == null ? undefined : json['tripName'],
        'inviteLink': json['inviteLink'] == null ? undefined : json['inviteLink'],
        'inviteToken': json['inviteToken'] == null ? undefined : json['inviteToken'],
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function TripInviteDtoToJSON(json: any): TripInviteDto {
    return TripInviteDtoToJSONTyped(json, false);
}

export function TripInviteDtoToJSONTyped(value?: TripInviteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'tripName': value['tripName'],
        'inviteLink': value['inviteLink'],
        'inviteToken': value['inviteToken'],
        'expiryDate': value['expiryDate'] == null ? value['expiryDate'] : value['expiryDate'].toISOString(),
        'isActive': value['isActive'],
    };
}

