/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripInviteInfoDto
 */
export interface TripInviteInfoDto {
    /**
     * 
     * @type {number}
     * @memberof TripInviteInfoDto
     */
    tripId?: number;
    /**
     * 
     * @type {string}
     * @memberof TripInviteInfoDto
     */
    tripName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripInviteInfoDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripInviteInfoDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TripInviteInfoDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TripInviteInfoDto
     */
    memberCount?: number;
    /**
     * 
     * @type {string}
     * @memberof TripInviteInfoDto
     */
    createdByName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TripInviteInfoDto
     */
    isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TripInviteInfoDto
     */
    message?: string | null;
}

/**
 * Check if a given object implements the TripInviteInfoDto interface.
 */
export function instanceOfTripInviteInfoDto(value: object): value is TripInviteInfoDto {
    return true;
}

export function TripInviteInfoDtoFromJSON(json: any): TripInviteInfoDto {
    return TripInviteInfoDtoFromJSONTyped(json, false);
}

export function TripInviteInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripInviteInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'tripName': json['tripName'] == null ? undefined : json['tripName'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'createdByName': json['createdByName'] == null ? undefined : json['createdByName'],
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TripInviteInfoDtoToJSON(json: any): TripInviteInfoDto {
    return TripInviteInfoDtoToJSONTyped(json, false);
}

export function TripInviteInfoDtoToJSONTyped(value?: TripInviteInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'tripName': value['tripName'],
        'description': value['description'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'memberCount': value['memberCount'],
        'createdByName': value['createdByName'],
        'isValid': value['isValid'],
        'message': value['message'],
    };
}

