/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripMemberDto } from './TripMemberDto';
import {
    TripMemberDtoFromJSON,
    TripMemberDtoFromJSONTyped,
    TripMemberDtoToJSON,
    TripMemberDtoToJSONTyped,
} from './TripMemberDto';

/**
 * 
 * @export
 * @interface TripDetailDto
 */
export interface TripDetailDto {
    /**
     * 
     * @type {number}
     * @memberof TripDetailDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TripDetailDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripDetailDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripDetailDto
     */
    currency?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripDetailDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TripDetailDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TripDetailDto
     */
    memberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TripDetailDto
     */
    totalSpent?: number;
    /**
     * 
     * @type {number}
     * @memberof TripDetailDto
     */
    yourShare?: number;
    /**
     * 
     * @type {number}
     * @memberof TripDetailDto
     */
    yourBalance?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TripDetailDto
     */
    isArchived?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TripDetailDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<TripMemberDto>}
     * @memberof TripDetailDto
     */
    members?: Array<TripMemberDto> | null;
}

/**
 * Check if a given object implements the TripDetailDto interface.
 */
export function instanceOfTripDetailDto(value: object): value is TripDetailDto {
    return true;
}

export function TripDetailDtoFromJSON(json: any): TripDetailDto {
    return TripDetailDtoFromJSONTyped(json, false);
}

export function TripDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'totalSpent': json['totalSpent'] == null ? undefined : json['totalSpent'],
        'yourShare': json['yourShare'] == null ? undefined : json['yourShare'],
        'yourBalance': json['yourBalance'] == null ? undefined : json['yourBalance'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(TripMemberDtoFromJSON)),
    };
}

export function TripDetailDtoToJSON(json: any): TripDetailDto {
    return TripDetailDtoToJSONTyped(json, false);
}

export function TripDetailDtoToJSONTyped(value?: TripDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'currency': value['currency'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'memberCount': value['memberCount'],
        'totalSpent': value['totalSpent'],
        'yourShare': value['yourShare'],
        'yourBalance': value['yourBalance'],
        'isArchived': value['isArchived'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(TripMemberDtoToJSON)),
    };
}

