/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripSummaryWithBalanceDto
 */
export interface TripSummaryWithBalanceDto {
    /**
     * 
     * @type {number}
     * @memberof TripSummaryWithBalanceDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TripSummaryWithBalanceDto
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripSummaryWithBalanceDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TripSummaryWithBalanceDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TripSummaryWithBalanceDto
     */
    memberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TripSummaryWithBalanceDto
     */
    totalExpenses?: number;
    /**
     * 
     * @type {number}
     * @memberof TripSummaryWithBalanceDto
     */
    yourBalance?: number;
    /**
     * 
     * @type {string}
     * @memberof TripSummaryWithBalanceDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TripSummaryWithBalanceDto
     */
    currencySymbol?: string | null;
}

/**
 * Check if a given object implements the TripSummaryWithBalanceDto interface.
 */
export function instanceOfTripSummaryWithBalanceDto(value: object): value is TripSummaryWithBalanceDto {
    return true;
}

export function TripSummaryWithBalanceDtoFromJSON(json: any): TripSummaryWithBalanceDto {
    return TripSummaryWithBalanceDtoFromJSONTyped(json, false);
}

export function TripSummaryWithBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripSummaryWithBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'totalExpenses': json['totalExpenses'] == null ? undefined : json['totalExpenses'],
        'yourBalance': json['yourBalance'] == null ? undefined : json['yourBalance'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'currencySymbol': json['currencySymbol'] == null ? undefined : json['currencySymbol'],
    };
}

export function TripSummaryWithBalanceDtoToJSON(json: any): TripSummaryWithBalanceDto {
    return TripSummaryWithBalanceDtoToJSONTyped(json, false);
}

export function TripSummaryWithBalanceDtoToJSONTyped(value?: TripSummaryWithBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'memberCount': value['memberCount'],
        'totalExpenses': value['totalExpenses'],
        'yourBalance': value['yourBalance'],
        'currency': value['currency'],
        'currencySymbol': value['currencySymbol'],
    };
}

