/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBalanceDto
 */
export interface UserBalanceDto {
    /**
     * 
     * @type {number}
     * @memberof UserBalanceDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserBalanceDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBalanceDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBalanceDto
     */
    avatar?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserBalanceDto
     */
    balance?: number;
}

/**
 * Check if a given object implements the UserBalanceDto interface.
 */
export function instanceOfUserBalanceDto(value: object): value is UserBalanceDto {
    return true;
}

export function UserBalanceDtoFromJSON(json: any): UserBalanceDto {
    return UserBalanceDtoFromJSONTyped(json, false);
}

export function UserBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'balance': json['balance'] == null ? undefined : json['balance'],
    };
}

export function UserBalanceDtoToJSON(json: any): UserBalanceDto {
    return UserBalanceDtoToJSONTyped(json, false);
}

export function UserBalanceDtoToJSONTyped(value?: UserBalanceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'currency': value['currency'],
        'avatar': value['avatar'],
        'balance': value['balance'],
    };
}

