/* tslint:disable */
/* eslint-disable */
/**
 * TripExpenseApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyBalanceDto } from './CurrencyBalanceDto';
import {
    CurrencyBalanceDtoFromJSON,
    CurrencyBalanceDtoFromJSONTyped,
    CurrencyBalanceDtoToJSON,
    CurrencyBalanceDtoToJSONTyped,
} from './CurrencyBalanceDto';
import type { TripSummaryWithBalanceDto } from './TripSummaryWithBalanceDto';
import {
    TripSummaryWithBalanceDtoFromJSON,
    TripSummaryWithBalanceDtoFromJSONTyped,
    TripSummaryWithBalanceDtoToJSON,
    TripSummaryWithBalanceDtoToJSONTyped,
} from './TripSummaryWithBalanceDto';

/**
 * 
 * @export
 * @interface UserDashboardDto
 */
export interface UserDashboardDto {
    /**
     * 
     * @type {number}
     * @memberof UserDashboardDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserDashboardDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDashboardDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDashboardDto
     */
    avatar?: string | null;
    /**
     * 
     * @type {Array<CurrencyBalanceDto>}
     * @memberof UserDashboardDto
     */
    currencyBalances?: Array<CurrencyBalanceDto> | null;
    /**
     * 
     * @type {number}
     * @memberof UserDashboardDto
     * @deprecated
     */
    overallBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDashboardDto
     */
    totalTrips?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDashboardDto
     */
    totalSpent?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDashboardDto
     */
    totalOwed?: number;
    /**
     * 
     * @type {Array<TripSummaryWithBalanceDto>}
     * @memberof UserDashboardDto
     */
    recentTrips?: Array<TripSummaryWithBalanceDto> | null;
}

/**
 * Check if a given object implements the UserDashboardDto interface.
 */
export function instanceOfUserDashboardDto(value: object): value is UserDashboardDto {
    return true;
}

export function UserDashboardDtoFromJSON(json: any): UserDashboardDto {
    return UserDashboardDtoFromJSONTyped(json, false);
}

export function UserDashboardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDashboardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'currencyBalances': json['currencyBalances'] == null ? undefined : ((json['currencyBalances'] as Array<any>).map(CurrencyBalanceDtoFromJSON)),
        'overallBalance': json['overallBalance'] == null ? undefined : json['overallBalance'],
        'totalTrips': json['totalTrips'] == null ? undefined : json['totalTrips'],
        'totalSpent': json['totalSpent'] == null ? undefined : json['totalSpent'],
        'totalOwed': json['totalOwed'] == null ? undefined : json['totalOwed'],
        'recentTrips': json['recentTrips'] == null ? undefined : ((json['recentTrips'] as Array<any>).map(TripSummaryWithBalanceDtoFromJSON)),
    };
}

export function UserDashboardDtoToJSON(json: any): UserDashboardDto {
    return UserDashboardDtoToJSONTyped(json, false);
}

export function UserDashboardDtoToJSONTyped(value?: UserDashboardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'email': value['email'],
        'avatar': value['avatar'],
        'currencyBalances': value['currencyBalances'] == null ? undefined : ((value['currencyBalances'] as Array<any>).map(CurrencyBalanceDtoToJSON)),
        'overallBalance': value['overallBalance'],
        'totalTrips': value['totalTrips'],
        'totalSpent': value['totalSpent'],
        'totalOwed': value['totalOwed'],
        'recentTrips': value['recentTrips'] == null ? undefined : ((value['recentTrips'] as Array<any>).map(TripSummaryWithBalanceDtoToJSON)),
    };
}

